BOOK_NAME=$(shell basename $(CURDIR))
TEXINPUTS=microtype:
FONTSDIR=fonts
TODAY=$(shell date --iso)
FORMAT=$(basename $(notdir $(FORMAT_FILE)))
TARGET_NAME=$(BOOK_NAME)_${FORMAT}
LATEX_INTERACTION=batchmode

all: $(TARGET_NAME).pdf

$(TARGET_NAME).tex: $(BOOK_NAME).tex ../../${FORMAT_FILE}
	@if [ "$(FORMAT)" = "" ]; then \
	     echo "FORMAT ARG is required"; \
	     exit 1; \
	 fi
	cat ../../${FORMAT_FILE} $(BOOK_NAME).tex > $@

$(TARGET_NAME).pdf: $(TARGET_NAME).tex
	OSFONTDIR=$(FONTSDIR) TEXINPUTS=$(TEXINPUTS) lualatex -shell-escape -interaction=$(LATEX_INTERACTION) $<
	rm -f $@
	OSFONTDIR=$(FONTSDIR) TEXINPUTS=$(TEXINPUTS) lualatex -shell-escape -interaction=$(LATEX_INTERACTION) $<
	rm -f $<

clean:
	rm -f *.pdf *.ps *.aux *.log *.out *.lol
	rm -f *.idx *.ind *.ilg *.toc *.dvi
